import type { Metadata } from "next";
import {Nunito, Nunito_Sans} from "next/font/google";
import "./globals.css";
import React from "react";
import Header from "@/components/header-components/header/Header";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${nunitoSans.variable} antialiased`}>
            <Header/>
        {children}
      </body>
    </html>
  );
}
